// Builds web/src/data/menu.ts from the scraped menu (lbs-site-data.json).
// Run: node scripts/build-menu.mjs <path-to-json>
import fs from 'node:fs';
const src = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const slug = s => s.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const CAT_META = {
  'Bandit Brews': { color: '#FF8F1F', kind: 'drink' },
  'Mutant Milks': { color: '#FF5CBE', kind: 'drink' },
  'Galaxy Sips':  { color: '#A58BFF', kind: 'drink' },
  'Elixirs':      { color: '#63E8CF', kind: 'drink' },
  'Salads':       { color: '#B8EE4F', kind: 'food' },
  'Soups':        { color: '#FF6A4D', kind: 'food' },
  'Starters':     { color: '#FFE24A', kind: 'food' },
  'Main Course':  { color: '#46BFD2', kind: 'food' },
  'Pasta':        { color: '#F4EBDD', kind: 'food' },
  'Pizza':        { color: '#FF4646', kind: 'food' },
  'Desserts':     { color: '#F2B8FF', kind: 'food' },
};
const ORDER = ['Bandit Brews','Galaxy Sips','Mutant Milks','Elixirs','Starters','Soups','Salads','Main Course','Pasta','Pizza','Desserts'];

const NONVEG = /\b(chicken|fish|prawns?|egg|calamari|carbonara)\b/i;
// Items whose veg status can't be read from the name: confirm with the cafe.
const UNKNOWN = new Set(['Recheado Masala','Mix Burnt Garlic Hakka Noodles','Mix Schezwan Noodles','Mixed Fried Rice','Herbed Rice','Lemongrass Rice','Mexican Rice']);

function diet(cat, name) {
  if (/\(Non-Veg\)/i.test(name) || /^Non-Veg\b/i.test(name)) return 'nonveg';
  if (/\(Veg\)/i.test(name)) return 'veg';
  if (UNKNOWN.has(name)) return 'unknown';
  if (cat === 'Desserts') return 'unknown';
  if (NONVEG.test(name)) return 'nonveg';
  return 'veg';
}

const cats = [];
for (const cname of ORDER) {
  const raw = src.menu[cname];
  const items = [];
  const byBase = new Map();
  for (const row of raw) {
    let [name, price, img, note] = row;
    let description;
    const m = name.match(/^Fruit Bowl \((.+)\)$/);
    if (m) { description = m[1].replace(/, /g, ', ').toLowerCase().replace(/^./, c => c.toUpperCase()); name = 'Fruit Bowl'; }
    const d = diet(cname, name);
    const pair = name.match(/^(.*) \((Veg|Non-Veg)\)$/);
    if (pair) {
      const base = pair[1];
      const opt = { label: pair[2] === 'Veg' ? 'Veg' : 'Non-veg', diet: d, price };
      if (byBase.has(base)) { byBase.get(base).options.push(opt); continue; }
      const it = { id: slug(cname + ' ' + base), name: base, options: [opt] };
      byBase.set(base, it); items.push(it); continue;
    }
    const it = { id: slug(cname + ' ' + name), name, options: [{ label: '', diet: d, price }] };
    if (description) it.description = description;
    if (note === 'has variants') it.hasVariants = true;
    items.push(it);
  }
  for (const it of items) it.options.sort((a, b) => (a.diet === 'veg' ? -1 : 1) - (b.diet === 'veg' ? -1 : 1));
  const prices = items.flatMap(i => i.options.map(o => o.price));
  cats.push({ id: slug(cname), name: cname, ...CAT_META[cname], min: Math.min(...prices), max: Math.max(...prices), items });
}

const header = `// Generated by scripts/build-menu.mjs from the old site's menu (lbs-cafe.foduu.com, Oct 2026).
// The live menu comes from the API; this copy is the fallback when the API can't be reached.
import type { MenuCategory } from './types';
`;
fs.writeFileSync('web/src/data/menu.ts', header + `export const MENU: MenuCategory[] = ${JSON.stringify(cats, null, 2)};\n`);
// The API seeds an empty database from the same data.
fs.mkdirSync('api/seed', { recursive: true });
fs.writeFileSync('api/seed/menu.json', JSON.stringify(cats, null, 2) + '\n');
const n = cats.reduce((a, c) => a + c.items.length, 0), o = cats.reduce((a, c) => a + c.items.reduce((b, i) => b + i.options.length, 0), 0);
console.log('categories', cats.length, 'rows', n, 'priced options', o);
console.log('unknown diet:', cats.flatMap(c => c.items.filter(i => i.options.some(x => x.diet === 'unknown')).map(i => i.name)).join(', '));
